#PBS -N f5c_call_methylation
#PBS -r n
#PBS -l mem=20GB,walltime=24:00:00,ncpus=35,ngpus=1
#PBS -q gpu
#PBS -m ae
#PBS -M email

module load gpu/cuda/10.0
module load gpu/f5c/0.3-beta

cd path/to/workingdirectory

f5c call-methylation -t 30 -r path/to/fastq.gz -b output.sorted.bam -g path/to/reference/genome/fasta -B 15.0M --iop 5 --cuda-dev-id 0 > name_of_output.tsv

f5c meth_freq -i name_of_output.tsv -o location/to/write/output.tsv -s 